name: Documentation Issue
description: Report an issue with documentation, examples, or guides
title: "[DOCS] "
labels: ["documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation!

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight Checklist
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - README
        - API Documentation
        - Examples
        - Code Comments
        - CHANGELOG
        - Contributing Guide
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue? (file path, URL, function name, etc.)
      placeholder: "src/lib.rs line 42, or examples/basic.rs, etc."
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect information
        - Outdated content
        - Typo/Grammar
        - Unclear explanation
        - Missing example
        - Broken link
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue
      placeholder: The documentation says... but it should say...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: I suggest...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional context that might be helpful