name: Feature Request
description: Suggest an idea or enhancement for the Twilight Relayer SDK
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight Checklist
      description: Please ensure you've completed these steps
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read the [Contributing Guidelines](../CONTRIBUTING.md)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Alternatives I've considered include...

  - type: textarea
    id: api-design
    attributes:
      label: API Design (if applicable)
      description: If this is an API change, show how you envision the new API
      render: rust
      placeholder: |
        // Proposed API usage
        use twilight_relayer_sdk::*;
        
        fn example() {
            // Your proposed API here
        }

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High - Blocks my work
        - Medium - Would significantly improve my workflow
        - Low - Nice to have
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of the SDK does this relate to?
      options:
        - Trading Operations
        - Lending Operations
        - Transaction Management
        - Error Handling
        - Documentation
        - Testing
        - Performance
        - Developer Experience
        - Other

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: I need this feature because...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
